name: flutterlenz_portfolio
description: "My portfolio for flutterlenz"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.5
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets_main/images/about/mission.jpg
    - assets_main/images/about/values.jpg
    - assets_main/images/about/vision.jpg
    - assets_main/images/fappproj/fileghost.png
    - assets_main/images/fappproj/qr4all_512.png
    - assets_main/images/fappproj/unitconverter-icon-512.png
    - assets_main/images/fappproj/wisp.png
    - assets_main/images/fappproj/wordpairapp_icon-512.png
    - assets_main/images/flutterlenz.png
    - assets_main/images/fappproj/mdlenz.png
  uses-material-design: true
